"""Code Agent — generate executable PINN experiment code from PDESpec + ArchitectureRec.

Two modes:
1. **Template-based** (default): fills a code template using the PDESpec and
   architecture recommendation. Deterministic, always correct, targets the
   ``pinn`` library API.
2. **LLM-generated**: asks the LLM to write the experiment code. More flexible
   but requires verification.

In both modes the generated code imports from the ``pinn`` library and follows
the same patterns as our hand-written experiments.
"""

from __future__ import annotations

import re
import textwrap

from llm_provider import LLMClient
from loguru import logger

from ..schemas import ArchitectureRec, PDESpec

# ---------------------------------------------------------------------------
# Template-based code generation
# ---------------------------------------------------------------------------

_CODE_TEMPLATE = textwrap.dedent('''\
    """Auto-generated PINN experiment: {name}

    Equation: {equation}
    Domain: {domain}
    Generated by Lang-PINN Code Agent.
    """

    import torch
    import torch.autograd as autograd
    import numpy as np
    from pinn import PINN, PINNTrainer, TrainingHealthMonitor, evaluate_quality

    # ---- Configuration ----
    SEED = 42
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    EPOCHS = {epochs}
    LR = {lr}
    N_COLLOCATION = {n_collocation}

    # ---- Model ----
    model = PINN(
        input_dim={input_dim},
        hidden_layers={hidden_layers},
        hidden_neurons={hidden_neurons},
        output_dim={output_dim},
        activation="{activation}",
    )

    # ---- Domain points ----
    {domain_code}

    # ---- Loss functions ----
    {loss_code}

    # ---- Training ----
    weights = {loss_weights}
    monitor = TrainingHealthMonitor(model, log_every=1000)
    trainer = PINNTrainer(model, device=DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=LR)

    trainer.train(
        n_epochs=EPOCHS,
        optimizer=optimizer,
        loss_functions=loss_functions,
        weights=weights,
        callbacks=[monitor],
    )

    # ---- Quality evaluation ----
    quality = evaluate_quality(trainer.loss_history)
    print(f"Quality score: {{quality['quality_score']:.3f}}")
    print(f"Health: {{monitor.report()}}")
''')


def generate_code_template(spec: PDESpec, arch: ArchitectureRec) -> str:
    """Generate experiment code from templates (deterministic, always valid).

    This produces runnable Python code that uses the ``pinn`` library API.
    """
    domain_code = _generate_domain_code(spec)
    loss_code = _generate_loss_code(spec)

    code = _CODE_TEMPLATE.format(
        name=spec.name,
        equation=spec.equation,
        domain=spec.domain,
        epochs=arch.epochs,
        lr=arch.learning_rate,
        n_collocation=arch.n_collocation,
        input_dim=arch.input_dim,
        hidden_layers=arch.hidden_layers,
        hidden_neurons=arch.hidden_neurons,
        output_dim=arch.output_dim,
        activation=arch.activation,
        domain_code=domain_code,
        loss_code=loss_code,
        loss_weights=repr(arch.loss_weights),
    )
    return code


def _generate_domain_code(spec: PDESpec) -> str:
    """Generate collocation point setup code."""
    lines = []
    for var, (lo, hi) in spec.domain.items():
        lines.append(
            f'{var}_pts = torch.linspace({lo}, {hi}, N_COLLOCATION)'
            f'.view(-1, 1).to(DEVICE).requires_grad_(True)'
        )

    if len(spec.independent_vars) == 1:
        var = spec.independent_vars[0]
        lines.append(f"collocation = {var}_pts")
    else:
        # Create meshgrid for multi-variable problems
        var_names = spec.independent_vars
        grids = ", ".join(f"{v}_pts.squeeze()" for v in var_names)
        lines.append(f"mesh = torch.meshgrid({grids}, indexing='ij')")
        lines.append(
            "collocation = torch.stack([m.reshape(-1) for m in mesh], dim=1)"
            ".to(DEVICE).requires_grad_(True)"
        )

    # IC points
    if spec.initial_conditions and "t" in spec.domain:
        t_lo = spec.domain["t"][0]
        lines.append(
            f"t_ic = torch.tensor([[{t_lo}]], dtype=torch.float32, "
            f"device=DEVICE, requires_grad=True)"
        )

    return "\n".join(lines)


def _generate_loss_code(spec: PDESpec) -> str:
    """Generate loss function code.

    For the template mode, we generate a placeholder PDE residual that the
    user can fill in. The structure follows our experiment convention.
    """
    lines = []

    # PDE residual — needs user/LLM to fill in the actual equation
    lines.append("def pde_residual(model, pts):")
    lines.append(f'    """PDE residual for: {spec.equation}"""')
    lines.append(f"    {spec.dependent_var} = model(pts)")

    # Generate derivative computation based on order
    var = spec.independent_vars[0]
    if spec.order >= 1:
        lines.append(
            f"    {spec.dependent_var}_{var} = autograd.grad("
            f"{spec.dependent_var}, pts, torch.ones_like({spec.dependent_var}), "
            f"create_graph=True)[0]"
        )
    if spec.order >= 2:
        lines.append(
            f"    {spec.dependent_var}_{var}{var} = autograd.grad("
            f"{spec.dependent_var}_{var}, pts, "
            f"torch.ones_like({spec.dependent_var}_{var}), "
            f"create_graph=True)[0]"
        )

    # Build the residual expression from the equation
    lines.append(f"    # Residual: {spec.equation}")
    lines.append(f"    residual = {spec.dependent_var}_{var}{var}  # TODO: complete residual")
    lines.append("    return residual")
    lines.append("")

    # Physics loss
    lines.append("def physics_loss(model):")
    lines.append("    return torch.mean(pde_residual(model, collocation) ** 2)")
    lines.append("")

    # IC loss
    if spec.initial_conditions:
        lines.append("def ic_loss(model):")
        lines.append(f"    {spec.dependent_var} = model(t_ic)")
        # Parse first IC for value
        lines.append(f"    return ({spec.dependent_var} - 1.0).pow(2).squeeze()  "
                      "# TODO: adjust IC value")
        lines.append("")

    # Build loss_functions dict
    loss_names = []
    if spec.initial_conditions:
        loss_names.append('"ic": ic_loss')
    loss_names.append('"physics": physics_loss')
    lines.append(f"loss_functions = {{{', '.join(loss_names)}}}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# LLM-generated code
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """\
You are a PINN code generation expert. Generate a complete, runnable Python \
script that solves the given PDE using the ``pinn`` library.

You MUST use these imports and patterns:
```python
import torch
import torch.autograd as autograd
import numpy as np
from pinn import PINN, PINNTrainer, TrainingHealthMonitor, evaluate_quality
```

Key patterns:
- ``PINN(input_dim=..., hidden_layers=..., hidden_neurons=..., output_dim=..., \
activation="tanh")`` to create the model
- ``PINNTrainer(model, device=device)`` to create the trainer
- Loss functions are callables: ``def my_loss(model) -> torch.Tensor``
- Derivatives via ``autograd.grad(u, t, torch.ones_like(u), create_graph=True)[0]``
- ``trainer.train(n_epochs=..., optimizer=..., loss_functions={...}, weights={...}, \
callbacks=[monitor])``

Return ONLY the Python code, no explanation. The code must be complete and runnable.
"""


class CodeAgent:
    """Generate experiment code from PDESpec and ArchitectureRec.

    Args:
        client: LLM client. Only needed if ``use_llm=True`` in :meth:`generate`.
    """

    def __init__(self, client: LLMClient | None = None):
        self.client = client

    def generate(
        self,
        spec: PDESpec,
        arch: ArchitectureRec,
        *,
        use_llm: bool = False,
    ) -> str:
        """Generate experiment code.

        Args:
            spec: Parsed PDE specification.
            arch: Architecture recommendation.
            use_llm: If True, ask the LLM to generate the code.
                If False, use deterministic template.

        Returns:
            Complete Python source code as a string.
        """
        if use_llm:
            return self._generate_llm(spec, arch)
        return generate_code_template(spec, arch)

    def _generate_llm(self, spec: PDESpec, arch: ArchitectureRec) -> str:
        if self.client is None:
            self.client = LLMClient()

        prompt = (
            f"Generate a PINN training script for this problem:\n\n"
            f"Name: {spec.name}\n"
            f"Equation: {spec.equation}\n"
            f"Variables: {spec.independent_vars} → {spec.dependent_var}\n"
            f"Domain: {spec.domain}\n"
            f"ICs: {spec.initial_conditions}\n"
            f"BCs: {spec.boundary_conditions}\n"
            f"Parameters: {spec.parameters}\n\n"
            f"Architecture to use:\n"
            f"- input_dim={arch.input_dim}, output_dim={arch.output_dim}\n"
            f"- hidden_layers={arch.hidden_layers}, hidden_neurons={arch.hidden_neurons}\n"
            f"- activation='{arch.activation}'\n"
            f"- epochs={arch.epochs}, lr={arch.learning_rate}\n"
            f"- n_collocation={arch.n_collocation}\n"
            f"- loss_weights={arch.loss_weights}\n"
        )
        if arch.use_ansatz:
            prompt += f"- Use {arch.ansatz_type} Ansatz\n"

        logger.info("Code Agent: asking LLM to generate experiment code")
        raw = self.client.ask(prompt, system=_SYSTEM_PROMPT)

        # Strip markdown fences if present
        code = _extract_code(raw)
        logger.info("Code Agent: generated {} lines of code", code.count('\n') + 1)
        return code


def _extract_code(text: str) -> str:
    """Extract Python code from LLM response."""
    text = text.strip()
    fence_match = re.search(r"```(?:python)?\s*\n(.*?)\n```", text, re.DOTALL)
    if fence_match:
        return fence_match.group(1).strip()
    return text
